ENV_CONCERTO_R_APP_URL = Sys.getenv("CONCERTO_R_APP_URL")
ENV_CONCERTO_R_CLIENT = Sys.getenv("CONCERTO_R_CLIENT")
ENV_CONCERTO_R_DB_CONNECTION = Sys.getenv("CONCERTO_R_DB_CONNECTION")
ENV_CONCERTO_R_INITIAL_PORT = Sys.getenv("CONCERTO_R_INITIAL_PORT")
ENV_CONCERTO_R_MAX_EXEC_TIME = Sys.getenv("CONCERTO_R_MAX_EXEC_TIME")
ENV_CONCERTO_R_MAX_IDLE_TIME = Sys.getenv("CONCERTO_R_MAX_IDLE_TIME")
ENV_CONCERTO_R_KEEP_ALIVE_TOLERANCE_TIME = Sys.getenv("CONCERTO_R_KEEP_ALIVE_TOLERANCE_TIME")
ENV_CONCERTO_R_PLATFORM_URL = Sys.getenv("CONCERTO_R_PLATFORM_URL")
ENV_CONCERTO_R_PUBLIC_DIR = Sys.getenv("CONCERTO_R_PUBLIC_DIR")
ENV_CONCERTO_R_REDIS_CONNECTION = Sys.getenv("CONCERTO_R_REDIS_CONNECTION")
ENV_CONCERTO_R_REQUEST = Sys.getenv("CONCERTO_R_REQUEST")
ENV_CONCERTO_R_RUNNER_TYPE = Sys.getenv("CONCERTO_R_RUNNER_TYPE")
ENV_CONCERTO_R_SESSION_HASH = Sys.getenv("CONCERTO_R_SESSION_HASH")
ENV_CONCERTO_R_SESSION_STORAGE = Sys.getenv("CONCERTO_R_SESSION_STORAGE")
ENV_CONCERTO_R_WORKING_DIR = Sys.getenv("CONCERTO_R_WORKING_DIR")
ENV_CONCERTO_R_SESSION_FILES_EXPIRATION = Sys.getenv("CONCERTO_R_SESSION_FILES_EXPIRATION")
ENV_CONCERTO_R_SERVICE_FIFO_PATH = Sys.getenv("CONCERTO_R_SERVICE_FIFO_PATH")

concerto5:::concerto.init(
    dbConnectionParams = fromJSON(ENV_CONCERTO_R_DB_CONNECTION),
    publicDir = ENV_CONCERTO_R_PUBLIC_DIR,
    platformUrl = ENV_CONCERTO_R_PLATFORM_URL,
    appUrl = ENV_CONCERTO_R_APP_URL,
    maxExecTime = as.numeric(ENV_CONCERTO_R_MAX_EXEC_TIME),
    maxIdleTime = as.numeric(ENV_CONCERTO_R_MAX_IDLE_TIME),
    keepAliveToleranceTime = as.numeric(ENV_CONCERTO_R_KEEP_ALIVE_TOLERANCE_TIME),
    sessionStorage = ENV_CONCERTO_R_SESSION_STORAGE,
    redisConnectionParams = ENV_CONCERTO_R_REDIS_CONNECTION,
    sessionFilesExpiration = fromJSON(ENV_CONCERTO_R_SESSION_FILES_EXPIRATION),
    serviceFifoDir = ENV_CONCERTO_R_SERVICE_FIFO_PATH
)

concerto5:::concerto.run(
    workingDir = ENV_CONCERTO_R_WORKING_DIR,
    client = fromJSON(ENV_CONCERTO_R_CLIENT),
    sessionHash = ENV_CONCERTO_R_SESSION_HASH,
    initialPort = ENV_CONCERTO_R_INITIAL_PORT,
    runnerType = ENV_CONCERTO_R_RUNNER_TYPE,
    response = fromJSON(ENV_CONCERTO_R_REQUEST)
)