<?php

namespace Concerto\APIBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthCodeRepository extends EntityRepository
{
}
