<?php

namespace Concerto\APIBundle\Repository;

use Concerto\PanelBundle\Repository\AEntityRepository;

/**
 * SamlTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SamlTokenRepository extends AEntityRepository
{
}
